package gtw

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/cnlangzi/nightme/internal/chatsession"
)

// RunPush is the entry point for `/gtw push`. Operates on the
// worktree identified by the .nightme/gtw.yml at the current
// CWD (same lookup strategy as RunClose). Flow:
//
//  1. Read yml → worktree, branch, mode, issue, repo, provider.
//  2. `git add -A` (or refuse if --no-commit and there are
//     uncommitted changes).
//  3. `git commit -m <auto-generated>` if anything got staged
//     in step 2.
//  4. `git push -u origin <branch>`.
//  5. If args.OpenPR: detect gh/glab, run `pr create` /
//     `mr create`. Fall back to printing the platform's
//     compare URL if neither CLI is installed.
//
// Reply is sent inline via deps.Send (matching the other Run*
// functions). On any error before the success card, we leave
// the worktree state alone — the user can retry or
// `git rebase --abort` / `git reset` manually.
func RunPush(
	ctx context.Context,
	cs *chatsession.ChatSession,
	deps HandlerDeps,
	chatID, messageID string,
	args pushArgs,
) (*Result, error) {
	selectedCwd, err := pushCwd()
	if err != nil {
		return reply(ctx, cs.Channel(), chatID, messageID,
			"❌ no active workspace. Send /cwd <path> first."), nil
	}

	// --- step 1: read yml ------------------------------
	c, err := ReadGTWYml(selectedCwd)
	if err != nil {
		if os.IsNotExist(err) {
			return reply(ctx, cs.Channel(), chatID, messageID,
				"❌ no active fix to push in this chat\n"+
					"hint: /cwd into the /gtw fix worktree first (its "+
					"`.nightme/gtw.yml` is the push source of truth)."), nil
		}
		return reply(ctx, cs.Channel(), chatID, messageID,
			fmt.Sprintf("❌ failed to read .nightme/gtw.yml: %v", err)), nil
	}
	if c.Worktree == "" || c.Branch == "" || c.RepoRoot == "" {
		return reply(ctx, cs.Channel(), chatID, messageID,
			"❌ .nightme/gtw.yml is malformed (worktree/branch/repoRoot required)"), nil
	}

	// --- step 2+3: dirty / commit ------------------------
	if err := commitIfNeeded(ctx, deps, c, args.NoCommit); err != nil {
		return reply(ctx, cs.Channel(), chatID, messageID, err.Error()), nil
	}

	// --- step 4: push ----------------------------------
	pushOut, err := pushBranch(ctx, deps, c)
	if err != nil {
		return reply(ctx, cs.Channel(), chatID, messageID,
			fmt.Sprintf("❌ git push failed: %v\n%s", err, pushOut)), nil
	}

	// --- step 5: PR (optional) --------------------------
	var prSection string
	if args.OpenPR {
		prOut, prURL, prErr := openPR(ctx, deps, c)
		switch {
		case prErr == nil:
			prSection = fmt.Sprintf(
				"━━━━━━━━━━━━━━\n"+
					"[Pull request]\n"+
					"🔗 %s\n%s",
				prURL, prOut)
		case prErr == errPRCLIMissing:
			// gh / glab not on PATH — fall back to the
			// platform's compare URL so the user can
			// finish the PR manually.
			compareURL := compareFallbackURL(c)
			prSection = fmt.Sprintf(
				"━━━━━━━━━━━━━━\n"+
					"[Pull request]\n"+
					"ℹ️  no `gh` or `glab` on PATH. Open the PR manually:\n"+
					"🔗 %s", compareURL)
		default:
			prSection = fmt.Sprintf(
				"━━━━━━━━━━━━━━\n"+
					"[Pull request]\n"+
					"❌ PR create failed: %v\n%s",
				prErr, prOut)
		}
	}

	// --- step 6: success card --------------------------
	body := fmt.Sprintf(
		"✅ Pushed %q\n"+
			"━━━━━━━━━━━━━━\n"+
			"[Push]\n"+
			"%s\n"+
			"[Context]\n"+
			"🌿 branch:   %s\n"+
			"📁 worktree: %s\n",
		c.Branch, indentLines(pushOut, "  "), c.Branch, c.Worktree,
	)
	body += prSection
	return reply(ctx, cs.Channel(), chatID, messageID, body), nil
}

// commitIfNeeded runs the dirty-check + auto-stage + commit
// step. Behaviour:
//
//   - `git status --porcelain` shows nothing → no commit
//     needed; return nil (push existing commits).
//   - `git status` shows staged/unstaged/untracked → stage
//     everything via `git add -A` and commit (unless
//     noCommit=true, in which case we refuse).
//   - `git status` shows unmerged paths (mid-rebase / merge
//     conflict) → refuse with a hint to abort.
//
// The commit message is auto-generated (see buildCommitMessage
// below) — users who want full control can commit manually
// before /gtw push.
func commitIfNeeded(ctx context.Context, deps HandlerDeps, c Context, noCommit bool) error {
	statusOut, _, err := deps.Git.Run(ctx, c.Worktree, "status", "--porcelain")
	if err != nil {
		return fmt.Errorf("git status: %w", err)
	}
	// Strip empty lines that git occasionally pads.
	statusLines := splitNonEmptyLines(statusOut)

	// Detect a mid-conflict state (rebase/merge) before we
	// try to commit — committing during a conflict produces a
	// "WIP: ..." commit that the user has to clean up
	// manually. Refuse early.
	for _, line := range statusLines {
		// Conflict markers start with "UU", "AA", "DD" etc.
		// (see git status --porcelain docs).
		if len(line) >= 2 {
			xy := line[:2]
			if xy[0] != ' ' && xy[1] != ' ' &&
				xy != "??" &&
				(xy[0] == 'U' || xy[1] == 'U' || xy[0] == 'A' || xy[1] == 'A') {
				return fmt.Errorf(
					"❌ worktree %s is in a conflicted state (unmerged paths present)\n"+
						"hint: resolve conflicts and `git add` the resolutions, OR `git rebase --abort` / `git merge --abort`",
					c.Worktree)
			}
		}
	}

	// No changes → skip commit.
	if len(statusLines) == 0 {
		return nil
	}

	// Changes present. Refuse or auto-stage.
	if noCommit {
		return fmt.Errorf(
			"❌ worktree %s has uncommitted changes (--no-commit)\n"+
				"  hint: commit them manually before /gtw push, OR drop --no-commit to auto-stage",
			c.Worktree)
	}

	if _, _, err := deps.Git.Run(ctx, c.Worktree, "add", "-A"); err != nil {
		return fmt.Errorf("git add -A: %w", err)
	}
	// Defensive double-check: re-read status AFTER add.
	// If nothing ended up staged (e.g. all changes were
	// in .gitignore), bail out cleanly.
	postAddOut, _, err := deps.Git.Run(ctx, c.Worktree, "status", "--porcelain")
	if err != nil {
		return fmt.Errorf("git status post-add: %w", err)
	}
	// After `add -A`, status still shows files with their
	// index status ('A ' / 'M ' etc.). The only way `postAdd`
	// would be empty is if everything was ignored. Treat
	// empty-postAdd as "no commit needed" rather than an
	// error — the existing commits still get pushed.
	if strings.TrimSpace(postAddOut) == "" {
		return nil
	}

	msg := buildCommitMessage(c)
	if _, _, err := deps.Git.Run(ctx, c.Worktree, "commit", "-m", msg); err != nil {
		return fmt.Errorf("git commit: %w", err)
	}
	return nil
}

// buildCommitMessage picks a sensible default commit message
// for the auto-commit. Format:
//
//   - ID-mode:    "#42: Add /gtw close subcommand"
//   - local-mode: the branch name (typically already descriptive)
//
// For ID-mode we use the yml's stored title if present, else
// fall back to the branch name. The yml doesn't currently
// store the issue body, so we don't try to embed it in the
// commit body — users who want richer context can amend.
func buildCommitMessage(c Context) string {
	if c.Issue > 0 {
		title := strings.TrimSpace(c.Branch)
		if title == "" {
			title = c.Branch
		}
		// In practice the branch already encodes the issue
		// number (e.g. "fix-42-..." or "42-..."). The yml
		// doesn't currently carry the issue title itself
		// (only the branch), so we just prefix with the
		// issue number for a clean log.
		return fmt.Sprintf("#%d: %s", c.Issue, c.Branch)
	}
	// local-mode: just the branch name.
	return c.Branch
}

// pushBranch runs `git push -u origin <branch>`. The
// -u flag sets upstream tracking so subsequent plain `git
// push` works without specifying the remote.
func pushBranch(ctx context.Context, deps HandlerDeps, c Context) (string, error) {
	stdout, stderr, err := deps.Git.Run(ctx, c.Worktree,
		"push", "-u", "origin", c.Branch)
	if err != nil {
		// git sometimes writes progress to stderr; the
		// tool's response is the union of stdout+stderr.
		combined := stdout + stderr
		return combined, fmt.Errorf("%w", err)
	}
	return stdout + stderr, nil
}

// openPR detects whether `gh` or `glab` is on PATH, then runs
// the appropriate `pr create` / `mr create` command. Returns
// (combined-output, public-url, error). The public URL is
// parsed from the CLI's stdout ("create pull request for X
// into main in OWNER/REPO" followed by the URL).
//
// When neither CLI is installed, returns errPRCLIMissing so
// the caller can fall back to a hand-rolled compare URL.
var errPRCLIMissing = fmt.Errorf("no gh/glab CLI installed")

func openPR(ctx context.Context, deps HandlerDeps, c Context) (string, string, error) {
	bin, err := detectPRCLI(c.Provider)
	if err != nil {
		return "", "", err
	}

	// Build the args. Note we deliberately don't pass --body /
	// --description for v1 — the issue body isn't in yml
	// yet (see Issue struct), and a one-line commit title
	// makes a serviceable first PR. The user can edit the
	// PR body in the web UI after creation.
	args := prCreateArgs(bin, c)

	// Run via os.exec (NOT deps.Git) — gh / glab aren't
	// git itself, and they have their own auth, output
	// formats, etc. We don't want to subject them to the
	// GitRunner abstraction.
	cmd := exec.CommandContext(ctx, bin, args...)
	cmd.Dir = c.Worktree
	stdout, stderr := &strings.Builder{}, &strings.Builder{}
	cmd.Stdout, cmd.Stderr = stdout, stderr
	if err := cmd.Run(); err != nil {
		return stdout.String() + stderr.String(), "",
			fmt.Errorf("%s pr create: %w (stderr: %s)", bin, err, stderr.String())
	}

	url := parsePRURL(stdout.String())
	return stdout.String() + stderr.String(), url, nil
}

// detectPRCLI returns "gh" for GitHub, "glab" for GitLab, or
// errPRCLIMissing if neither is installed. Lookup is a single
// exec.LookPath per CLI (cheap, no subprocess).
func detectPRCLI(provider string) (string, error) {
	var bin string
	switch provider {
	case "github", "":
		bin = "gh"
	case "gitlab":
		bin = "glab"
	default:
		// Unknown provider — default to gh (best-effort).
		bin = "gh"
	}
	if _, err := exec.LookPath(bin); err != nil {
		return "", errPRCLIMissing
	}
	return bin, nil
}

// prCreateArgs builds the argv for `gh pr create` /
// `glab mr create`. Kept separate from openPR for testability
// (tests assert the exact argv).
//
// Format choices:
//
//   - gh: `pr create --title <t> --head <branch> --base <default>
//          [--body <b>]`
//   - glab: `mr create --title <t> --target-branch <default>
//           --head <branch> [--description <b>]`
//
// `--base` / `--target-branch` defaults to "main" — covers
// the overwhelmingly common case. Users with a non-main
// default branch can amend the PR URL.
func prCreateArgs(bin string, c Context) []string {
	title := buildCommitMessage(c) // sensible default
	base := "main"
	switch bin {
	case "gh":
		return []string{
			"pr", "create",
			"--title", title,
			"--head", c.Branch,
			"--base", base,
		}
	case "glab":
		return []string{
			"mr", "create",
			"--title", title,
			"--target-branch", base,
			"--head", c.Branch,
		}
	}
	return nil
}

// parsePRURL extracts the first https URL from gh/glab
// stdout. Both CLIs print the PR URL on success ("…
// https://github.com/owner/repo/pull/123" / "…
// https://gitlab.com/owner/repo/-/merge_requests/4").
func parsePRURL(out string) string {
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "https://") {
			return line
		}
	}
	return ""
}

// compareFallbackURL returns the platform-specific
// "compare two branches" URL so the user can open a PR by
// clicking once. Format follows GitHub / GitLab conventions.
//
//   - GitHub: https://github.com/<owner>/<repo>/compare/<base>...<head>
//   - GitLab: https://gitlab.com/<owner>/<repo>/-/compare/<base>...<head>
//
// The owner/repo comes from yml's Repo field (which is the
// "owner/repo" form).
func compareFallbackURL(c Context) string {
	host := "github.com"
	prefix := "compare"
	if c.Provider == "gitlab" {
		host = "gitlab.com"
		prefix = "-/compare"
	}
	return fmt.Sprintf("https://%s/%s/%s/main...%s",
		host, c.Repo, prefix, c.Branch)
}

// indentLines prefixes every line of s with prefix. Used for
// multi-line stdout (git push progress) in the success card
// so the indentation reads as a code block.
func indentLines(s, prefix string) string {
	if s == "" {
		return ""
	}
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, line := range lines {
		lines[i] = prefix + line
	}
	return strings.Join(lines, "\n")
}

// pushCwd returns the current working directory of the
// daemon. Used as the source-of-truth for "where is the
// user right now" when looking up the .nightme/gtw.yml.
//
// Implementation note: we shell out to `pwd` because
// os.Getwd() reads the daemon's CWD (not the chat's). Each
// chat's CWD is held in chatsession, but a slash command
// doesn't have direct access to it from here — the
// HandlerDeps passed by the factory wrapper has the chatID
// but not the *chatsession.ChatSession. The factory would
// need a small refactor (pass the cs through, like runFix
// does) to read the per-chat CWD without shelling out.
//
// We accept the subprocess cost (one `pwd` per /gtw push,
// ~1ms) for now to keep the diff small. Future: thread cs
// through the factory's push handler the same way runFix
// already does.
func pushCwd() (string, error) {
	cmd := exec.Command("pwd")
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("pwd: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}