// Package main — embedded byte payloads for the system-tray icon.
//
// systray.SetIcon / systray.SetTemplateIcon / systray.SetTitle all
// take raw byte slices, and the daemon child does not have a
// usable working directory at startup (it is launched by `nightme
// start` via proc.New, with stdin/stdout/stderr pointed at /dev/null
// and a stderr-capture file). Reading the assets off disk at
// runtime would require a path resolution that depends on the
// install layout and would race the file's existence.
//
// //go:embed is the right answer: the assets are baked into the
// binary at compile time, and the runtime call is just a slice
// header. The cost is binary size (~7 KB for Windows + ~1 KB for
// each of three macOS sizes + ~6 KB Linux), which is negligible.
//
// Asset layout (under cmd/nightme/assets/):
//
//   - logo-32.ico     : Windows 32x32 ICO (multi-resolution .ico
//                       generated by go-winres from logo.ico).
//                       Used by systray.SetIcon on Windows; the
//                       taskbar already shows the PE-embedded
//                       icon from the .syso, but systray needs
//                       its own copy.
//   - trayTemplate*.png : macOS menu-bar template (alpha-only
//                         black mask, three sizes for 1x/2x/3x).
//                         Used by systray.SetTemplateIcon. Cocoa
//                         auto-inverts in dark mode.
//   - tray.png        : Linux system-tray icon (64x64 RGBA).
//                       Used by systray.SetIcon on Linux.
//
// Platform gating is handled at the call site (cmd/nightme/tray.go
// uses build tags); the embed itself is unconditional because the
// //go:embed compiler insists that every referenced file exist,
// and that is exactly the property we want (a Linux build that
// references a missing tray.png should fail at compile time, not
// at first launch).

package main

import _ "embed"

//go:embed assets/logo-32.ico
var logoICO32 []byte

//go:embed assets/trayTemplate.png
var trayTemplatePNG []byte

//go:embed assets/trayTemplate@2x.png
var trayTemplatePNG2x []byte

//go:embed assets/trayTemplate@3x.png
var trayTemplatePNG3x []byte

//go:embed assets/tray.png
var trayPNG []byte

// IconWindows returns the byte payload for the Windows systray
// icon. Built from a 32x32 ICO (one of the multi-resolution
// variants produced by go-winres; the taskbar already uses the
// full multi-res .ico, systray wants this one).
func IconWindows() []byte { return logoICO32 }

// IconDarwin returns the macOS menu-bar template icon bytes
// (alpha-only black mask, three sizes packed as a single
// multi-resolution PNG via SetTemplateIcon's 3-arg form). The
// caller passes them to systray.SetTemplateIcon(template1x,
// template2x, template3x).
func IconDarwin() (one, two, three []byte) {
	return trayTemplatePNG, trayTemplatePNG2x, trayTemplatePNG3x
}

// IconLinux returns the Linux system-tray icon bytes (64x64 RGBA
// PNG).
func IconLinux() []byte { return trayPNG }
