// Package main — embedded byte payloads for the system-tray icon.
//
// systray.SetIcon / systray.SetTemplateIcon / systray.SetTitle all
// take raw byte slices, and the daemon child does not have a
// usable working directory at startup (it is launched by `nightme
// start` via proc.New, with stdin/stdout/stderr pointed at /dev/null
// and a stderr-capture file). Reading the assets off disk at
// runtime would require a path resolution that depends on the
// install layout and would race the file's existence.
//
// //go:embed is the right answer: the assets are baked into the
// binary at compile time, and the runtime call is just a slice
// header. The cost is binary size (~7 KB for Windows + ~1 KB for
// each of three macOS sizes + ~6 KB Linux), which is negligible.
//
// Asset layout (under cmd/nightme/assets/):
//
//   - logo-32.ico     : Windows 32x32 ICO (multi-resolution .ico
//                       generated by go-winres from logo.ico).
//                       Used by systray.SetIcon on Windows; the
//                       taskbar already shows the PE-embedded
//                       icon from the .syso, but systray needs
//                       its own copy.
//   - trayTemplate*.png : macOS menu-bar template (alpha-only
//                         black mask, three sizes for 1x/2x/3x).
//                         Used by systray.SetTemplateIcon. Cocoa
//                         auto-inverts in dark mode.
//   - tray.png        : Linux system-tray icon (64x64 RGBA).
//                       Used by systray.SetIcon on Linux.
//
// Platform gating is handled at the call site (cmd/nightme/tray.go
// uses build tags); the embed itself is unconditional because the
// //go:embed compiler insists that every referenced file exist,
// and that is exactly the property we want (a Linux build that
// references a missing tray.png should fail at compile time, not
// at first launch).

package main

import _ "embed"

// //go:embed is a compiler directive, but the embed package
// must still be in the import set of the file that uses it.
// The blank import is the conventional form for the
// "directive only" case — we bind the embedded bytes to
// package-level []byte variables and never reach for
// embed.FS at runtime, so the package itself contributes
// nothing beyond compiler metadata.

//go:embed assets/logo-32.ico
var logoICO32 []byte

//go:embed assets/trayTemplate.png
var trayTemplatePNG []byte

//go:embed assets/trayTemplate@2x.png
var trayTemplatePNG2x []byte

//go:embed assets/trayTemplate@3x.png
var trayTemplatePNG3x []byte

//go:embed assets/tray.png
var trayPNG []byte

// IconWindows returns the byte payload for the Windows systray
// icon. Built from a 32x32 ICO (one of the multi-resolution
// variants produced by go-winres; the taskbar already uses the
// full multi-res .ico, systray wants this one).
func IconWindows() []byte { return logoICO32 }

// IconDarwin returns the (template, regular) icon bytes for
// macOS. systray.SetTemplateIcon takes exactly two []byte:
// the template (alpha-only mask that Cocoa auto-inverts for
// dark menu bars) and the regular (a non-template fallback
// used when the host does not honour the template flag).
//
// We pass a single 22x22 template; Cocoa scales it via NSImage
// for HiDPI on its own (the @2x / @3x PNGs in the assets
// directory are kept as dev-side regenerable sources but not
// fed to systray — the API doesn't take multi-resolution
// input). The regular fallback is the same 64x64 PNG we ship
// for Linux; macOS scales it for the menu bar too.
func IconDarwin() (template, regular []byte) {
	return trayTemplatePNG, trayPNG
}

// IconLinux returns the Linux system-tray icon bytes (64x64 RGBA
// PNG).
func IconLinux() []byte { return trayPNG }
