package wiki

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Page contracts — Wiki.md §6.
//
// Each contract is the canonical Markdown shape the Agent must
// emit for that page kind. ModulePrompt / ArchitecturePrompt /
// QuickstartPrompt render the same contract into the Wiki
// Prompt (§11.3) so the Agent has a single source of truth for
// what a valid page looks like.

const moduleContract = `## Module page contract

Required headings (in order):

# <basename of source path>

> One short paragraph stating the observable responsibility.

## Purpose
One short paragraph describing the module's responsibility.

## Entry Points
The smallest set of types, functions, registries, or factories
worth reading first. Use Source Anchor syntax (see below).

## Main Flows
No more than three concise paths from entry to output. Each
flow: "<start symbol> → <end symbol> via <intermediates>".

## Related Modules
Direct relationships, each as a markdown link to the
neighbour's module page (use the relative path).

## Where to Change
Common change targets and the source or test area each lives in.

## Source Anchors
Repository-relative paths and symbol names. Each line is either:

    - <relative/path/to/file.go>
    - <relative/path/to/file.go>::<FuncName>
    - <relative/path/to/file.go>::<TypeName>.<MethodName>

Symbol names are best-effort; a missing symbol is a warning,
not a failure (Wiki.md §12 "best-effort and language-aware").
File paths are mandatory.

Forbidden content:
  - Complete exported API lists
  - File-by-file line-count tables
  - Long code excerpts
  - Design intent not stated in code
  - Coding rules duplicated from AGENTS.md
  - [TBD] placeholders
`

const architectureContract = `## Architecture page contract

Required headings (in order):

# Architecture

## Components
Groups of major responsibilities, each linking to one or more
module pages. Components do NOT redefine module identity — they
cluster modules by role.

## Entry Points
Binaries, servers, workers, slash commands, plugin registries,
and the source paths that anchor them.

## Main Flows
A small number of end-to-end paths (typically 2–5). Each flow
names the start symbol, the end symbol, and the intermediates.

## Dependency Direction
Major dependencies present in code, stated as "A depends on B
because <observable call sites / types>". Do not infer design
intent.

## Extension Points
Interfaces, registration functions, factories, and adapters
where new behaviour can be plugged in without modifying
existing call sites.

## Cross-cutting Concerns
Error handling, persistence, concurrency, platform splits, and
configuration hotspots — point at the module pages that own
each.

## Source Anchors
Repository-relative paths and symbol names, same syntax as
module pages.

Forbidden content:
  - ADRs or design rationale not in the code
  - Speculation about why the design exists
  - [TBD] placeholders
`

const quickstartContract = `## Quickstart page contract

Required headings (in order):

# Quickstart

## Repository Rules
Where the project's coding and workflow rules live (e.g.
AGENTS.md). One short paragraph.

## Development Setup
The exact commands to get a working build (e.g. make build,
make test). Derive from Makefile, package manifests, CI config,
and development scripts. Do NOT invent commands.

## Find the Relevant Code
How to locate code for a coding task: directory conventions,
discovery commands, common entry points. Reference the wiki
itself (llms.txt is the discovery entry point).

## Make a Focused Change
How to scope a change to the right module pages (mention
wiki.yml.pending and the /wiki regeneration cadence).

## Verify
The exact commands from the project's verify contract
(formatting, test, lint, build). Do NOT repeat the README's
end-user tutorial — that stays in README.

Forbidden content:
  - Product installation / end-user tutorials (those live in
    README)
  - Speculative workflow advice
  - [TBD] placeholders
`

// rootIndex renders wiki/llms.txt (§6.1). project is the
// display name; children is the slice of top-level source
// areas to link under "## Areas". quickstart/architecture
// are always linked from "## Start" when their pages exist.
func rootIndex(project string, children []areaLink, quickstartPath, archPath string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", project)

	b.WriteString("> Generated by /wiki. Code is authoritative; verify against source before editing.\n\n")

	b.WriteString("## Start\n\n")
	b.WriteString("- [Quickstart](")
	b.WriteString(quickstartPath)
	b.WriteString("): Locate code and run repository verification.\n")
	b.WriteString("- [Architecture](")
	b.WriteString(archPath)
	b.WriteString("): Cross-module components and main flows.\n\n")

	b.WriteString("## Rules\n\n")
	b.WriteString("- [Agent Instructions](../AGENTS.md): Build, test, style, and runtime constraints.\n\n")

	if len(children) > 0 {
		b.WriteString("## Areas\n\n")
		for _, c := range children {
			fmt.Fprintf(&b, "- [%s](%s): %s\n", c.Name, c.RelPath, c.Description)
		}
	}
	return b.String()
}

// areaLink is a child area entry in rootIndex or a directory
// index. Description is rendered as the link's trailing text.
type areaLink struct {
	Name        string
	RelPath     string
	Description string
}

// dirIndex renders a directory llms.txt (§6.2). The "This
// module" section is omitted when selfHasPage is false (the
// directory contains no direct source files and only links to
// children).
func dirIndex(name, description string, selfHasPage bool, selfRelPath string, children []areaLink) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", name)
	if description != "" {
		fmt.Fprintf(&b, "> %s\n\n", description)
	}

	if selfHasPage {
		b.WriteString("## This module\n\n")
		fmt.Fprintf(&b, "- [Overview](%s): Direct contents of this directory.\n\n", selfRelPath)
	}

	if len(children) > 0 {
		b.WriteString("## Children\n\n")
		for _, c := range children {
			fmt.Fprintf(&b, "- [%s](%s): %s\n", c.Name, c.RelPath, c.Description)
		}
	}
	return b.String()
}

// emptyModulePage renders an empty-but-valid module page —
// the §11.4 fallback when a prior agent run was interrupted
// and the on-disk page already matches the contract shape but
// contains no real content. Plan can finalize it without
// re-dispatching when validation passes.
func emptyModulePage(pkgPath string) string {
	title := filepath.Base(pkgPath)
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", title)
	b.WriteString("> Stub module page. Purpose / Entry Points / Source Anchors pending.\n\n")
	b.WriteString("## Purpose\n\n\n")
	b.WriteString("## Entry Points\n\n\n")
	b.WriteString("## Main Flows\n\n\n")
	b.WriteString("## Related Modules\n\n\n")
	b.WriteString("## Where to Change\n\n\n")
	b.WriteString("## Source Anchors\n\n")
	return b.String()
}

// buildHierarchicalIndexes walks the live module list and
// produces deterministic llms.txt files at every directory
// that owns or contains modules. Returns the list of paths
// written (relative to repoRoot), for the final reply.
//
// §13 "Deterministic root and directory indexes rebuild on
// every /wiki finalization, including no-op finalization." This
// is the single rendering entry point.
func buildHierarchicalIndexes(repoRoot string, yml *wikiYml) ([]string, error) {
	written := make([]string, 0, 16)

	live := liveModules(yml)
	tree := buildAreaTree(live)

	// Directory indexes: every directory that contains at
	// least one module, plus the modules/ root if there are
	// any live modules.
	for dir, kids := range tree.byDir {
		// Build child links for this directory.
		var children []areaLink
		for _, k := range kids {
			children = append(children, areaLink{
				Name:        filepath.Base(k),
				RelPath:     indexRel(k),
				Description: purposeFor(yml, k),
			})
		}
		sort.Slice(children, func(i, j int) bool { return children[i].Name < children[j].Name })

		selfHasPage := hasOwnPage(dir, live)
		selfRel := indexRel(dir) + "/index.md"
		body := dirIndex(
			humanDirLabel(dir),
			areaDescription(dir),
			selfHasPage,
			selfRel,
			children,
		)
		out := filepath.Join(repoRoot, "wiki", "modules", indexRel(dir), "llms.txt")
		if err := atomicWrite(out, body); err != nil {
			return written, err
		}
		written = append(written, filepath.ToSlash(filepath.Join("wiki", "modules", indexRel(dir), "llms.txt")))
	}

	// Root llms.txt.
	var rootKids []areaLink
	for _, k := range tree.roots {
		rootKids = append(rootKids, areaLink{
			Name:        filepath.Base(k),
			RelPath:     "modules/" + indexRel(k) + "/llms.txt",
			Description: purposeFor(yml, k),
		})
	}
	sort.Slice(rootKids, func(i, j int) bool { return rootKids[i].Name < rootKids[j].Name })

	project := filepath.Base(repoRoot)
	body := rootIndex(project, rootKids, "quickstart.md", "architecture.md")
	rootOut := filepath.Join(repoRoot, "wiki", "llms.txt")
	if err := atomicWrite(rootOut, body); err != nil {
		return written, err
	}
	written = append(written, "wiki/llms.txt")

	return written, nil
}

// areaTree is the result of grouping live modules by their
// top-most source directory.
type areaTree struct {
	roots []string            // top-level area paths (depth-1 relative to repoRoot)
	byDir map[string][]string // dir path → direct module paths
}

func buildAreaTree(modules []string) areaTree {
	t := areaTree{byDir: map[string][]string{}}
	for _, m := range modules {
		// Module belongs to its parent dir; the parent dir
		// belongs to ITS parent, etc. We seed every directory
		// along the path so dir indexes render even when the
		// leaf has no own source files.
		dir := filepath.Dir(m)
		for dir != "." && dir != "/" {
			t.byDir[dir] = append(t.byDir[dir], m)
			dir = filepath.Dir(dir)
		}
	}
	for _, v := range t.byDir {
		sort.Strings(v)
	}
	// Roots = directories with no parent in the tree.
	hasParent := map[string]bool{}
	for d := range t.byDir {
		p := filepath.Dir(d)
		if p != "." && p != "/" {
			hasParent[d] = true
		}
	}
	for d := range t.byDir {
		if !hasParent[d] {
			t.roots = append(t.roots, d)
		}
	}
	sort.Strings(t.roots)
	return t
}

func liveModules(yml *wikiYml) []string {
	var out []string
	for _, m := range yml.Modules {
		if m.Removed {
			continue
		}
		if m.Path == "" {
			continue
		}
		out = append(out, m.Path)
	}
	return out
}

func purposeFor(yml *wikiYml, path string) string {
	for _, m := range yml.Modules {
		if m.Path == path {
			if m.Purpose != "" {
				return m.Purpose
			}
			return filepath.Base(path)
		}
	}
	return filepath.Base(path)
}

func hasOwnPage(dir string, liveModules []string) bool {
	for _, m := range liveModules {
		if filepath.Dir(m) == dir {
			return true
		}
	}
	return false
}

// indexRel turns a source-area path into the wiki-relative
// path used by llms.txt links. Module paths map 1:1 to
// `modules/<source-path>/index.md`.
func indexRel(p string) string {
	return filepath.ToSlash(p)
}

// humanDirLabel is the display name for a directory index. Falls
// back to the basename; uses the full relative path when the
// directory IS the root.
func humanDirLabel(dir string) string {
	if dir == "" || dir == "." {
		return "/"
	}
	return dir
}

func areaDescription(dir string) string {
	// Minimal descriptor; richer descriptions arrive from the
	// architecture page once it's generated. Keeping this
	// short avoids asking the LLM to author prose here.
	return filepath.Base(dir) + " source area."
}

// scaffoldEmptyRecovery creates an empty wiki/ tree on disk
// when the metadata says the wiki exists but wiki/ has gone
// missing (§9 state-reconciliation row 2). The wiki.yml is
// written by the caller after this returns.
func scaffoldEmptyRecovery(repoRoot string, yml *wikiYml) error {
	dirs := []string{
		filepath.Join(repoRoot, "wiki"),
		filepath.Join(repoRoot, "wiki", "modules"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return err
		}
	}
	for _, m := range yml.Modules {
		if m.Removed || m.Path == "" {
			continue
		}
		out := filepath.Join(repoRoot, "wiki", "modules", m.File)
		if err := atomicWrite(out, emptyModulePage(m.Path)); err != nil {
			return err
		}
	}
	return nil
}
