// Package outbound — translator from agent.AgentEvent to the
// abstract gateway.OutboundMessage stream. The translator is an
// outbound concern (not a Channel concern) because:
//
//   - AgentEvent is part of the agent protocol; only the outbound
//     package speaks it.
//   - OutboundMessage is the abstract wire format that Channels
//     consume. Channels do not see AgentEvent.
//   - Translation may need to merge multiple AgentEvents into one
//     OutboundMessage (e.g. OutToolStart + OutToolEnd pair collapsing
//     into a single line in the rolled log) — an outbound-level
//     decision. Channels render the result.
//
// The current translator is a 1:1 mapping: one AgentEvent produces
// one OutboundMessage. Channels like Feishu may further roll the
// OutboundMessage stream into a single edited message (see F-25
// v0.3 + F-26 Stage 3).
//
// Moved from internal/gateway/translate.go in the F-?-outbound
// refactor — see package doc for the broader rationale.
package outbound

import (
	"fmt"
	"strings"

	"github.com/cnlangzi/nightme/internal/agent"
	"github.com/cnlangzi/nightme/internal/gateway"
)

// thinkingPrefix is the sentinel the claudecode bridge prepends to
// every thinking block before emitting EventAgentText. Renderer.render
// (and Channel-specific renderers) use it to tell thinking from a
// final reply and surface them with different icons (💭 vs 💬).
const thinkingPrefix = "[思考] "

// Translate converts one agent.AgentEvent into the abstract
// gateway.OutboundMessage stream. Returns the message to send and a
// boolean indicating whether anything should be sent at all:
//
//   - (msg, true)  → Emitter.Send / Emitter.SendCard should send msg
//   - (zero, false) → drop (e.g. terminal events that have no
//     user-facing content; the receipt already reflects the
//     final state)
//
// Terminal events (Done, Error) are NOT emitted as separate
// OutboundMessages; the receipt's terminal header carries that
// signal. Permission events are mapped to OutCard; the Channel
// renders the card natively (Feishu interactive, Slack block kit,
// Web HTML).
func Translate(chatID string, ev agent.AgentEvent) (gateway.OutboundMessage, bool) {
	switch ev.Kind {
	case agent.EventAgentText:
		text := strings.TrimSpace(ev.Text)
		if text == "" {
			return gateway.OutboundMessage{}, false
		}
		if strings.HasPrefix(text, thinkingPrefix) {
			return gateway.OutboundMessage{
				ChatID: chatID,
				Kind:   gateway.OutThinking,
				Text:   strings.TrimPrefix(text, thinkingPrefix),
			}, true
		}
		return gateway.OutboundMessage{
			ChatID: chatID,
			Kind:   gateway.OutReply,
			Text:   text,
		}, true

	case agent.EventAgentToolStart:
		if ev.ToolStart == nil {
			return gateway.OutboundMessage{}, false
		}
		name := ev.ToolStart.Name
		if name == "" {
			name = "tool"
		}
		// Outbound only transports the unified ToolInfo —
		// channel decides how to render "🔧 name(args)" or its
		// own equivalent. Outbound does NOT pre-format Text
		// (removed) or stash per-tool fields in Meta (those were
		// Feishu-specific implicit keys leaking into the
		// abstract layer; see F-34 review P0-2 / Devin
		// architecture feedback 2026-08-04).
		return gateway.OutboundMessage{
			ChatID: chatID,
			Kind:   gateway.OutToolStart,
			Tool: &gateway.ToolInfo{
				Name: name,
				Args: ev.ToolStart.Args,
			},
		}, true

	case agent.EventAgentToolEnd:
		if ev.ToolEnd == nil {
			return gateway.OutboundMessage{}, false
		}
		name := ev.ToolEnd.Name
		if name == "" {
			name = "tool"
		}
		// Same as EventAgentToolStart above — ToolInfo carries the
		// generic fields; outbound does not format Text or use
		// Meta for tool data.
		return gateway.OutboundMessage{
			ChatID: chatID,
			Kind:   gateway.OutToolEnd,
			Tool: &gateway.ToolInfo{
				Name:   name,
				Args:   ev.ToolEnd.Args,
				Output: ev.ToolEnd.Output,
				Err:    ev.Err,
			},
		}, true

	case agent.EventAgentPermission:
		if ev.Permission == nil {
			return gateway.OutboundMessage{}, false
		}
		req := ev.Permission
		return gateway.OutboundMessage{
			ChatID: chatID,
			Kind:   gateway.OutCard,
			Card: &gateway.Card{
				Title:   "Permission needed",
				Body:    req.Tool + ": " + req.Action,
				Options: req.Options,
				// RequestID is generated by the Channel when it
				// actually renders the card (Feishu's interactive
				// card.value field is filled in at the Channel layer
				// so the inbound Action.RequestID matches).
			},
		}, true

	case agent.EventAgentDone, agent.EventAgentError:
		// Terminal events are reflected in the receipt's terminal
		// header; the Stage 3 Feishu renderer flips the reaction
		// emoji and edits the header line. We don't emit a separate
		// OutboundMessage for them here.
		//
		// Translate is a pass-through — runtime (newEventHandler in
		// cmd/nightme/run.go) does NOT read Done.Usage separately;
		// per-turn Usage flows exclusively from EventAgentResult.Usage
		// (co-located with the final assistant reply). Bridges that
		// only emit EventAgentDone-with-Usage and no EventAgentResult will not
		// see their Usage reach the channel footer — by design
		// (F-45 §1.5 / F-52).
		return gateway.OutboundMessage{}, false

	case agent.EventAgentResult:
		// Final assistant reply (Claude Code: result.Result).
		// Distinct from EventAgentText so channels can render it with a
		// dedicated icon (📝) instead of as a rolling-log entry.
		// We emit even when Text is empty AND IsError is true so
		// the channel can flip its header to an error state.
		if ev.Result == nil {
			return gateway.OutboundMessage{}, false
		}
		if ev.Result.Text == "" && ev.Err == nil {
			return gateway.OutboundMessage{}, false
		}
		out := gateway.OutboundMessage{
			ChatID: chatID,
			Kind:   gateway.OutResult,
			Text:   ev.Result.Text,
			Result: ev.Result,
		}
		// Bridges populate ev.Result.Usage from the same wire event
		// they took Text from (Claude Code result.usage +
		// result.modelUsage; Pi message_end.usage on the assistant
		// role). Co-locating the usage on the OutResult eliminates
		// the EventAgentResult-then-EventUsage ordering hazard that
		// forced the runtime to buffer OutResult. nil usage
		// (zero-usage turn / synthetic message) is fine — the
		// runtime is a passive pass-through, so a nil Usage just
		// means the channel footer omits Line 2.
		if u := ev.Result.Usage; u != nil {
			out.Usage = (*gateway.UsageInfo)(u)
		}
		return out, true

	case agent.EventAgentReady:
		// Session bootstrap (Claude Code: system/init). Carries
		// session_id + model; channels surface them in the receipt
		// header so users can identify the session for /resume.
		// agent_name + workspace are forwarded too so the Feishu
		// receipt card's foot note can render
		// "Agent | cwd · tokens" (see docs/channel/feishu.md §9.3).
		//
		// Note: bridges always stamp the 5 context fields on every
		// event (incl. EventAgentReady), so we just pass them
		// through. No "if Ready != nil" guard needed.
		return gateway.OutboundMessage{
			ChatID:    chatID,
			Kind:      gateway.OutInit,
			Text:      fmt.Sprintf("session initialized (model: %s)", ev.Model),
			SessionID: ev.SessionID,
			Model:     ev.Model,
			AgentName: ev.AgentName,
			Workspace: ev.Workspace,
			Branch:    ev.Branch,
		}, true

	case agent.EventAgentTaskCreate:
		// F-38: full task snapshot replaces the per-turn checklist.
		// The Feishu adapter writes it into the current receipt and
		// PATCHes the card; other Channels may render or drop.
		// The bridge MUST only emit this after a confirmed success
		// result (see internal/bridge/claudecode/task.go).
		if ev.TaskList == nil {
			return gateway.OutboundMessage{}, false
		}
		return gateway.OutboundMessage{
			ChatID:   chatID,
			Kind:     gateway.OutTaskCreate,
			TaskList: ev.TaskList,
		}, true

	case agent.EventAgentTaskUpdate:
		// F-38: subsequent mutations / deletions. Same snapshot
		// semantics as EventAgentTaskCreate; an empty Items slice is a
		// valid "clear the checklist" signal (e.g. all tasks done).
		if ev.TaskList == nil {
			return gateway.OutboundMessage{}, false
		}
		return gateway.OutboundMessage{
			ChatID:   chatID,
			Kind:     gateway.OutTaskUpdate,
			TaskList: ev.TaskList,
		}, true
	}
	return gateway.OutboundMessage{}, false
}