// Package gateway — translator from agent.AgentEvent to the
// abstract OutboundMessage stream. The translator is a Gateway
// concern (not a Channel concern) because:
//
//   - AgentEvent is part of the agent protocol; only the Gateway
//     speaks it.
//   - OutboundMessage is the abstract wire format that Channels
//     consume. Channels do not see AgentEvent.
//   - Translation may need to merge multiple AgentEvents into one
//     OutboundMessage (e.g. OutToolStart + OutToolEnd pair collapsing
//     into a single line in the rolled log) — a Gateway-level
//     decision. Channels render the result.
//
// The current translator is a 1:1 mapping: one AgentEvent produces
// one OutboundMessage. Channels like Feishu may further roll
// OutboundMessage stream into a single edited message (see F-25
// v0.3 + F-26 Stage 3).
package gateway

import (
	"fmt"
	"strings"

	"github.com/cnlangzi/nightme/internal/agent"
)

// thinkingPrefix is the sentinel the claudecode bridge prepends to
// every thinking block before emitting EventText. Renderer.render
// (and Channel-specific renderers) use it to tell thinking from a
// final reply and surface them with different icons (💭 vs 💬).
const thinkingPrefix = "[思考] "

// Translate converts one agent.AgentEvent into the abstract
// OutboundMessage stream. Returns the message to send and a
// boolean indicating whether anything should be sent at all:
//
//   - (msg, true)  → Channel should send msg
//   - (zero, false) → Channel should drop (e.g. terminal events that
//     have no user-facing content; the receipt
//     already reflects the final state)
//
// Terminal events (Done, Error) are NOT emitted as separate
// OutboundMessages; the receipt's terminal header carries that
// signal. Permission events are mapped to OutCard; the Channel
// renders the card natively (Feishu interactive, Slack block kit,
// Web HTML).
func Translate(chatID string, ev agent.AgentEvent) (OutboundMessage, bool) {
	switch ev.Kind {
	case agent.EventText:
		text := strings.TrimSpace(ev.Text)
		if text == "" {
			return OutboundMessage{}, false
		}
		if strings.HasPrefix(text, thinkingPrefix) {
			return OutboundMessage{
				ChatID: chatID,
				Kind:   OutThinking,
				Text:   strings.TrimPrefix(text, thinkingPrefix),
			}, true
		}
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutText,
			Text:   text,
		}, true

	case agent.EventToolStart:
		if ev.ToolStart == nil {
			return OutboundMessage{}, false
		}
		name := ev.ToolStart.Name
		if name == "" {
			name = "tool"
		}
		// Gateway only transports the unified ToolInfo —
		// channel decides how to render "🔧 name(args)" or its
		// own equivalent. Gateway does NOT pre-format Text
		// (removed) or stash per-tool fields in Meta (those were
		// Feishu-specific implicit keys leaking into the
		// abstract layer; see F-34 review P0-2 / Devin
		// architecture feedback 2026-08-04).
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutToolStart,
			Tool: &ToolInfo{
				Name: name,
				Args: ev.ToolStart.Args,
			},
		}, true

	case agent.EventToolEnd:
		if ev.ToolEnd == nil {
			return OutboundMessage{}, false
		}
		name := ev.ToolEnd.Name
		if name == "" {
			name = "tool"
		}
		// Same as EventToolStart above — ToolInfo carries the
		// generic fields; gateway does not format Text or use
		// Meta for tool data.
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutToolEnd,
			Tool: &ToolInfo{
				Name:   name,
				Args:   ev.ToolEnd.Args,
				Output: ev.ToolEnd.Output,
				Err:    ev.ToolEnd.Err,
			},
		}, true

	case agent.EventPermission:
		if ev.Permission == nil {
			return OutboundMessage{}, false
		}
		req := ev.Permission
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutCard,
			Card: &Card{
				Title:   "Permission needed",
				Body:    req.Tool + ": " + req.Action,
				Options: req.Options,
				// RequestID is generated by the Channel when it
				// actually renders the card (Feishu's interactive
				// card.value field is filled in at the Channel layer
				// so the inbound Action.RequestID matches).
			},
		}, true

	case agent.EventDone, agent.EventError:
		// Terminal events are reflected in the receipt's terminal
		// header; the Stage 3 Feishu renderer flips the reaction
		// emoji and edits the header line. We don't emit a separate
		// OutboundMessage for them here.
		return OutboundMessage{}, false

	case agent.EventResult:
		// Final assistant reply (Claude Code: result.Result).
		// Distinct from EventText so channels can render it with a
		// dedicated icon (📝) instead of as a rolling-log entry.
		// We emit even when Text is empty AND IsError is true so
		// the channel can flip its header to an error state.
		if ev.Result == nil {
			return OutboundMessage{}, false
		}
		if ev.Result.Text == "" && !ev.Result.IsError {
			return OutboundMessage{}, false
		}
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutResult,
			Text:   ev.Result.Text,
			Result: ev.Result,
		}, true

	case agent.EventUsage:
		// Per-turn token usage (Claude Code: result.usage +
		// result.modelUsage). Channels render it as a footer line.
		if ev.Usage == nil {
			return OutboundMessage{}, false
		}
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutUsage,
			Text:   formatUsageSummary(ev.Usage),
			Usage: &UsageInfo{
				InputTokens:              ev.Usage.InputTokens,
				OutputTokens:             ev.Usage.OutputTokens,
				CacheCreationInputTokens: ev.Usage.CacheCreationInputTokens,
				CacheReadInputTokens:     ev.Usage.CacheReadInputTokens,
				CostUSD:                  ev.Usage.CostUSD,
			},
		}, true

	case agent.EventCompaction:
		// Mid-turn context compaction — NOT a turn end. Channels
		// surface "✶ Compacting conversation…" briefly so users
		// know why the agent paused.
		//
		// The Subtype field is currently unused by any channel;
		// if a future channel needs it, add it as a typed field
		// on OutboundMessage rather than smuggling it through Meta.
		text := "✶ Compacting conversation…"
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutCompaction,
			Text:   text,
		}, true

	case agent.EventInit:
		// Session bootstrap (Claude Code: system/init). Carries
		// session_id + model; channels surface them in the receipt
		// header so users can identify the session for /resume.
		// agent_name + workspace are forwarded too so the Feishu
		// receipt card's foot note can render
		// "Agent | cwd | tokens" (see docs/channel/feishu.md §9.3).
		if ev.Init == nil {
			return OutboundMessage{}, false
		}
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutInit,
			Text:   fmt.Sprintf("session initialized (model: %s)", ev.Init.Model),
			Init:   ev.Init,
		}, true
	}
	return OutboundMessage{}, false
}

// formatUsageSummary renders a one-line usage summary suitable for
// log lines / footer text. Returns "" when all counts are zero
// (caller decides whether to drop the OutboundMessage).
//
// Shape (v0.3): "<N> tokens[ · $X.XXXX]" — the context-window
// percentage requires a model-aware denominator that we don't carry
// yet; v0.4 will add ContextWindow to UsageEvent and extend this.
func formatUsageSummary(u *agent.UsageEvent) string {
	total := u.InputTokens + u.OutputTokens + u.CacheCreationInputTokens + u.CacheReadInputTokens
	if total == 0 {
		return ""
	}
	if u.CostUSD > 0 {
		return fmt.Sprintf("%s tokens · $%.4f", humanTokens(total), u.CostUSD)
	}
	return fmt.Sprintf("%s tokens", humanTokens(total))
}

// humanTokens renders a token count with k-suffix rounding. Mirrors
// the conventions used in Claude Code's own CLI output ("1.2k",
// "12k"). Values < 1000 are returned verbatim so small counts stay
// precise.
func humanTokens(n int) string {
	switch {
	case n < 1000:
		return fmt.Sprintf("%d", n)
	case n < 10000:
		return fmt.Sprintf("%.1fk", float64(n)/1000)
	default:
		return fmt.Sprintf("%dk", n/1000)
	}
}
