// Package gateway — translator from agent.AgentEvent to the
// abstract OutboundMessage stream. The translator is a Gateway
// concern (not a Channel concern) because:
//
//   - AgentEvent is part of the agent protocol; only the Gateway
//     speaks it.
//   - OutboundMessage is the abstract wire format that Channels
//     consume. Channels do not see AgentEvent.
//   - Translation may need to merge multiple AgentEvents into one
//     OutboundMessage (e.g. OutToolStart + OutToolEnd pair collapsing
//     into a single line in the rolled log) — a Gateway-level
//     decision. Channels render the result.
//
// The current translator is a 1:1 mapping: one AgentEvent produces
// one OutboundMessage. Channels like Feishu may further roll
// OutboundMessage stream into a single edited message (see F-25
// v0.3 + F-26 Stage 3).
package gateway

import (
	"fmt"
	"strings"

	"github.com/cnlangzi/nightme/internal/agent"
)

// thinkingPrefix is the sentinel the claudecode bridge prepends to
// every thinking block before emitting EventText. Renderer.render
// (and Channel-specific renderers) use it to tell thinking from a
// final reply and surface them with different icons (💭 vs 💬).
const thinkingPrefix = "[思考] "

// Translate converts one agent.AgentEvent into the abstract
// OutboundMessage stream. Returns the message to send and a
// boolean indicating whether anything should be sent at all:
//
//   - (msg, true)  → Channel should send msg
//   - (zero, false) → Channel should drop (e.g. terminal events that
//                      have no user-facing content; the receipt
//                      already reflects the final state)
//
// Terminal events (Done, Error) are NOT emitted as separate
// OutboundMessages; the receipt's terminal header carries that
// signal. Permission events are mapped to OutCard; the Channel
// renders the card natively (Feishu interactive, Slack block kit,
// Web HTML).
func Translate(chatID string, ev agent.AgentEvent) (OutboundMessage, bool) {
	switch ev.Kind {
	case agent.EventText:
		text := strings.TrimSpace(ev.Text)
		if text == "" {
			return OutboundMessage{}, false
		}
		if strings.HasPrefix(text, thinkingPrefix) {
			return OutboundMessage{
				ChatID: chatID,
				Kind:   OutThinking,
				Text:   strings.TrimPrefix(text, thinkingPrefix),
			}, true
		}
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutText,
			Text:   text,
		}, true

	case agent.EventToolStart:
		if ev.ToolStart == nil {
			return OutboundMessage{}, false
		}
		name := ev.ToolStart.Name
		if name == "" {
			name = "tool"
		}
		text := name
		if ev.ToolStart.Args != "" {
			text = name + "(" + ev.ToolStart.Args + ")"
		}
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutToolStart,
			Text:   text,
			Meta: map[string]any{
				"tool_name": name,
				"args":      ev.ToolStart.Args,
			},
		}, true

	case agent.EventToolEnd:
		if ev.ToolEnd == nil {
			return OutboundMessage{}, false
		}
		name := ev.ToolEnd.Name
		if name == "" {
			name = "tool"
		}
		var text string
		var iconKind OutboundKind = OutToolEnd
		if ev.ToolEnd.Err != nil {
			iconKind = OutToolEnd
			text = fmt.Sprintf("%s failed: %s", name, ev.ToolEnd.Err.Error())
		} else if ev.ToolEnd.Output != "" {
			text = fmt.Sprintf("%s → %s", name, ev.ToolEnd.Output)
		} else {
			text = name + " done"
		}
		_ = iconKind
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutToolEnd,
			Text:   text,
			Meta: map[string]any{
				"tool_name": name,
				"output":    ev.ToolEnd.Output,
				"err":       ev.ToolEnd.Err,
			},
		}, true

	case agent.EventPermission:
		if ev.Permission == nil {
			return OutboundMessage{}, false
		}
		req := ev.Permission
		return OutboundMessage{
			ChatID: chatID,
			Kind:   OutCard,
			Card: &Card{
				Title:   "Permission needed",
				Body:    req.Tool + ": " + req.Action,
				Options: req.Options,
				// RequestID is generated by the Channel when it
				// actually renders the card (Feishu's interactive
				// card.value field is filled in at the Channel layer
				// so the inbound Action.RequestID matches).
			},
		}, true

	case agent.EventDone, agent.EventError:
		// Terminal events are reflected in the receipt's terminal
		// header; the Stage 3 Feishu renderer flips the reaction
		// emoji and edits the header line. We don't emit a separate
		// OutboundMessage for them here.
		return OutboundMessage{}, false
	}
	return OutboundMessage{}, false
}
